package com.mybatis.demo.entity;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbg.generated Tue Aug 15 21:04:45 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.name
     *
     * @mbg.generated Tue Aug 15 21:04:45 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.tel_num
     *
     * @mbg.generated Tue Aug 15 21:04:45 CST 2017
     */
    private String telNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.a_id
     *
     * @mbg.generated Tue Aug 15 21:04:45 CST 2017
     */
    private Integer aId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     *
     * @mbg.generated Tue Aug 15 21:04:45 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     *
     * @mbg.generated Tue Aug 15 21:04:45 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.name
     *
     * @return the value of user.name
     *
     * @mbg.generated Tue Aug 15 21:04:45 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.name
     *
     * @param name the value for user.name
     *
     * @mbg.generated Tue Aug 15 21:04:45 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.tel_num
     *
     * @return the value of user.tel_num
     *
     * @mbg.generated Tue Aug 15 21:04:45 CST 2017
     */
    public String getTelNum() {
        return telNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.tel_num
     *
     * @param telNum the value for user.tel_num
     *
     * @mbg.generated Tue Aug 15 21:04:45 CST 2017
     */
    public void setTelNum(String telNum) {
        this.telNum = telNum == null ? null : telNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.a_id
     *
     * @return the value of user.a_id
     *
     * @mbg.generated Tue Aug 15 21:04:45 CST 2017
     */
    public Integer getaId() {
        return aId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.a_id
     *
     * @param aId the value for user.a_id
     *
     * @mbg.generated Tue Aug 15 21:04:45 CST 2017
     */
    public void setaId(Integer aId) {
        this.aId = aId;
    }

	@Override
	public String toString() {
		return "User [id=" + id + ", name=" + name + ", telNum=" + telNum + ", aId=" + aId + "]";
	}
    
}